---
name: Unit Tests

on: # NOLINT
  pull_request:
  push:
  schedule:
    - cron: '0 10 * * MON'
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04, ubuntu-22.04, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade wheel
          python -m pip install --upgrade mypy
          python -m pip install --upgrade tox
          python -m pip install --upgrade tox-gh-actions
          python -m pip install --upgrade virtualenv
          python -m pip install -r requirements.txt

      - name: Install tools (Linux)
        if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-22.04'
        run: |
          git clone https://github.com/KCL-Planning/VAL
          cd VAL/scripts/linux
          sh build_linux64.sh all Release
          cd ../../..
          mkdir -p /opt/val/bin/
          cp -r VAL/build/linux64/Release/install/bin/* /opt/val/bin/
          rm -rf VAL

      - name: Mypy
        run: |
          mypy --ignore-missing-imports --strict src/

      - name: Statick Markdown
        if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-22.04'
        uses: sscpac/statick-action@v0.0.2
        with:
          profile: documentation.yaml

      - name: Sphinx lint
        if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-22.04'
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: 'docs/'

      - name: Tox
        run: |
          python -m tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false

      - name: Statick
        if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-22.04'
        uses: sscpac/statick-action@v0.0.2
        with:
          profile: self_check.yaml
